import Head from 'next/head';
import ReservoirTab from '@/components/reservoir/ReservoirTab';

export default function Home() {
  return (
    <>
      <Head>
        <title>อ่างเก็บน้ำ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <div className='mt-[2rem] mb-[2rem] flex flex-col gap-[2rem]'>
          <ReservoirTab />
        </div>
      </main>
    </>
  );
}
