import WaterLevelTable from '@/components/waterlevel/WaterLevelTable'
import Head from 'next/head'
import React from 'react'

const index = () => {
  return (
    <>
      <Head>
        <title>ระดับน้ำ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className='mt-[2rem] mb-[2rem] flex flex-col gap-[2rem]'>
          <WaterLevelTable />
        </div>
      </main>
    </>
  )
}

export default index